name: Smart Notification Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install Dependencies
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt

      - name : Deploy to Production
        run: |
              python manage.py makemigrations
              python manae.py migrate
              python manage.py runserver




      


